volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nokvix/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: nokvix/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    depends_on:
      - backend
    volumes:
      - static:/static
  gateway:
    image: nokvix/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/static
      - media:/app/media
